stripe_api/payment/urls.py
from django.urls import (
    path,
)

from .views import (
    ApiItem,
    ApiPayment,
    CancelPaymentView,
    index,
    SuccessPaymentView,
)

app_name = 'payment'

#
urlpatterns = [
    path('', index),
    path('item/<int:pk>', ApiItem.as_view(), name='item-detail'),
    path('buy/<int:pk>', ApiPayment.as_view(), name='item-buy'),
    path('success/', SuccessPaymentView.as_view()),
    path('cancel/', CancelPaymentView.as_view()),
]

stripe_api/stripe_api/urls.py
from django.contrib import admin
from django.urls import (
    include,
    path,
)

urlpatterns = [
    path('', include('payment.urls')),
    path('admin/', admin.site.urls),
]

stripe_api/payment/models.py
from django.db import models


class Item(models.Model):
    """Model items to buy them"""
    name = models.CharField(verbose_name='Название продукта', unique=True, max_length=25)
    description = models.CharField(verbose_name='Описание', max_length=250)
    price = models.PositiveIntegerField(verbose_name='Стоимость')

    def __str__(self):
        return self.name

    @property
    def stripe_price(self):
        return self.price * 100

stripe_api/payment/views.py
import os

from django.http import (
    JsonResponse,
    HttpResponseRedirect,
)
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView
from dotenv import load_dotenv
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView
import stripe

from .models import Item
from .serializers import ItemSerializer

load_dotenv()

stripe.api_key = os.environ.get('STRIPE_SECRET_KEY')


def index(request):
    return HttpResponseRedirect('/item/1')


class ApiPayment(APIView):
    def get(self, request, pk):
        item = get_object_or_404(Item, pk=pk)
        session = stripe.checkout.Session.create(
            line_items=[{
                'price_data': {
                    'currency': 'rub',
                    'unit_amount': item.stripe_price,
                    'product_data': {
                        'name': item.name
                    }
                },
                'quantity': 1
            }],
            mode='payment',
            success_url=request.build_absolute_uri('/success/'),
            cancel_url=request.build_absolute_uri('/cancel/')
        )
        return JsonResponse({'id': session.id})


class ApiItem(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'payment/item_detail.html'

    def get(self, request, pk):
        item = get_object_or_404(Item, pk=pk)
        serializer = ItemSerializer(item)
        return Response({'serializer': serializer, 'item': item})


class SuccessPaymentView(TemplateView):
    template_name = 'payment/success.html'


class CancelPaymentView(TemplateView):
    template_name = 'payment/cancel.html'

stripe_api/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    {% load static %}
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <script src="https://js.stripe.com/v3/"></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script defer src="{% static 'js/buy.js' %}"></script>
  </head>
  <body>
    <main>
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </main>
  </body>
</html>

stripe_api/templates/payment/cancel.html
{% extends "base.html" %}
{% block content %}

<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="alert alert-primary" role="alert">
              Нам очень жаль, что вы отменили свой заказ :( Будем рады вас видесть снова!
            </div>
            <a href="/">на главную</a>
        </div>
    </div>
</div>

{% endblock %}

stripe_api/templates/payment/item_detail.html
{% extends "base.html" %}
{% block content %}

<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card" >
                <div class="card-header">
                  Покупаемый товар
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        {% for field in serializer %}

                        <li class="list-group-item">
                            <div class="d-flex flex-row w-100">
                                <div class="d-flex w-100"><b>{{ field.label }}:</b></div>
                                <div class="d-flex w-100">{{ field.value }}</div>
                            </div>
                        </li>

                        {% endfor %}
                    </ul>
                </div>
                <button type="submit" class="btn btn-primary" id="buy-button">Buy</button>
            </div>
        </div>
    </div>
</div>
<script>
    document.addEventListener("DOMContentLoaded", function(){
        buy(url="{% url 'payment:item-buy' item.pk %}");
    });
</script>

{% endblock %}

stripe_api/templates/payment/success.html
{% extends "base.html" %}
{% block content %}

<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="alert alert-success" role="alert">
              Ваша оплата прошла успешно!
            </div>
          <a href="/">на главную</a>
        </div>
    </div>
</div>

{% endblock %}